---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[freetds::default]
  - name: source
    run_list:
      - recipe[freetds::default]
    attributes:
      freetds:
        install_method: source
