---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: debian-7.4
    run_list:
    - recipe[apt]
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[freetds::default]
    excludes:
      - centos-6.6
  - name: source
    run_list:
      - recipe[freetds::default]
    attributes:
      freetds:
        install_method: source
